"""Static HTML renderer for Phase 0.

Two-column parchment view: each event is one row with both agents' takes
side by side. Pure Python — no templating engine — to keep deps minimal.
"""

from __future__ import annotations

import html
from pathlib import Path
from typing import Iterable

from ..schema import ChronicleEvent
from ..storage import Store


PAGE_CSS = """
:root {
  --parchment: #f3e7c9;
  --parchment-dark: #e6d3a3;
  --ink: #2b1d10;
  --ink-soft: #5b4326;
  --rule: #b69963;
  --accent: #7a1f1f;
}
* { box-sizing: border-box; }
body {
  margin: 0;
  font-family: 'Cormorant Garamond', 'EB Garamond', 'Georgia', serif;
  background: var(--parchment);
  color: var(--ink);
  line-height: 1.55;
}
header {
  padding: 3rem 2rem 1rem;
  border-bottom: 1px solid var(--rule);
  text-align: center;
}
header h1 {
  font-size: 2.4rem;
  font-weight: 600;
  margin: 0;
  letter-spacing: 0.02em;
}
header .subtitle {
  color: var(--ink-soft);
  font-style: italic;
  margin-top: 0.3rem;
}
header .stats {
  margin-top: 0.8rem;
  font-size: 0.85rem;
  color: var(--ink-soft);
}
main {
  max-width: 1200px;
  margin: 0 auto;
  padding: 2rem;
}
.event {
  margin: 2.5rem 0;
  padding: 1.5rem;
  background: rgba(255,255,255,0.18);
  border: 1px solid var(--rule);
  border-radius: 4px;
}
.event-meta {
  font-size: 0.85rem;
  color: var(--ink-soft);
  border-bottom: 1px solid var(--rule);
  padding-bottom: 0.6rem;
  margin-bottom: 1rem;
  display: flex;
  justify-content: space-between;
  flex-wrap: wrap;
  gap: 0.5rem;
}
.event-meta .year {
  font-weight: 600;
  color: var(--accent);
  font-size: 1rem;
}
.columns {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 1.5rem;
}
@media (max-width: 760px) {
  .columns { grid-template-columns: 1fr; }
}
.col {
  padding: 0.5rem 0.2rem;
}
.col h3 {
  margin: 0 0 0.2rem;
  font-size: 0.78rem;
  letter-spacing: 0.18em;
  text-transform: uppercase;
  color: var(--ink-soft);
  font-weight: 600;
}
.col h2 {
  margin: 0.3rem 0 0.8rem;
  font-size: 1.2rem;
  color: var(--accent);
  font-style: italic;
}
.col .body p {
  margin: 0 0 0.6em;
}
.col.empty .body {
  color: #999;
  font-style: italic;
}
footer {
  text-align: center;
  padding: 2rem;
  color: var(--ink-soft);
  font-size: 0.8rem;
  border-top: 1px solid var(--rule);
}
"""


PAGE_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>{title}</title>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<style>{css}</style>
</head>
<body>
<header>
  <h1>{title}</h1>
  <div class="subtitle">{subtitle}</div>
  <div class="stats">{stats}</div>
</header>
<main>
{events_html}
</main>
<footer>
  Generated by CK3 AI Chronicler — Phase 0
</footer>
</body>
</html>
"""


def render_html(
    store: Store,
    output_path: str | Path,
    *,
    title: str = "Chronicles of the Realm",
    subtitle: str = "A multi-perspective history",
    events: Iterable[ChronicleEvent] | None = None,
) -> Path:
    events_list = list(events) if events is not None else store.list_events()
    parts: list[str] = []
    total_cost = store.total_cost()
    for event in events_list:
        rows = store.list_chronicles_for_event(event.event_id)
        by_agent = {r["agent"]: r for r in rows}
        primary = event.primary_actors[0]
        meta = (
            f'<div class="event-meta">'
            f'<span><span class="year">AD {event.year}</span> · {html.escape(event.type.value)}</span>'
            f'<span>{html.escape(primary.name)}'
            + (f' of {html.escape(primary.dynasty)}' if primary.dynasty else "")
            + "</span>"
            f"</div>"
        )
        cols = []
        for agent_name, label in (
            ("court_historian", "Court Chronicle"),
            ("peasant_ballad", "Folk Ballad"),
        ):
            row = by_agent.get(agent_name)
            if row:
                cols.append(_col_html(label, row["title"], row["body"]))
            else:
                cols.append(_col_empty_html(label))
        parts.append(
            f'<section class="event">{meta}<div class="columns">{"".join(cols)}</div></section>'
        )
    stats = (
        f"{len(events_list)} events · "
        f"total LLM spend ${total_cost:.4f}"
    )
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        PAGE_TEMPLATE.format(
            title=html.escape(title),
            subtitle=html.escape(subtitle),
            stats=html.escape(stats),
            css=PAGE_CSS,
            events_html="\n".join(parts) if parts else "<p><em>No events recorded yet.</em></p>",
        ),
        encoding="utf-8",
    )
    return out


def _col_html(label: str, title: str, body: str) -> str:
    paragraphs = "".join(
        f"<p>{html.escape(p.strip())}</p>" for p in body.split("\n\n") if p.strip()
    ) or f"<p>{html.escape(body)}</p>"
    return (
        f'<div class="col">'
        f"<h3>{html.escape(label)}</h3>"
        f"<h2>{html.escape(title)}</h2>"
        f'<div class="body">{paragraphs}</div>'
        f"</div>"
    )


def _col_empty_html(label: str) -> str:
    return (
        f'<div class="col empty">'
        f"<h3>{html.escape(label)}</h3>"
        f'<div class="body">(no entry yet)</div>'
        f"</div>"
    )
